\c worth_a_shot

INSERT INTO users (name, age, gender, zip_code, personality, flavors, atmosphere, firebase_id) VALUES
('John Wick', 42, 'male', '10003', 'introvert', 'bitter', 'lounges, jazzandblues, musicvenues', '100'),
('Anne Hathaway', 40, 'female', '10002', 'extrovert', 'sweet, sour', 'cocktailbars, danceclubs', '101'),
('Leonardo DiCaprio', 48, 'male', '10038', 'ambivert', 'sour, bitter', 'danceclubs, adultentertainment, cocktailbars, lounges', '102');

INSERT INTO alcohols (name, ingredients, proof, description, category, flavors, type, image) VALUES
('Stella Artois', 'Water, Malted Barley, Maize, Saaz Hops', 10, 'This beer is great for its herbal and malty sweetness, with a smooth yet bitter aftertaste. One of the more popular beers to order.', 'beer', 'Bitter', 'fermented', 'https://www.liquor.com/thmb/ZqR-JXRwqWVgUTnc9ShkyzM3uu4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/bottle-review_stella-artois_720x720-af8a80477721421d9ad26e22d79f50c7.jpg'),
('Heineken Beer', 'Water, Malted Barley, Hop Extract, Yeast', 10, 'A sweet and sour beer that often has a hint of green apple and sweet corn. A good beer to sit back and drink with friends.', 'beer', 'Bitter', 'fermented', 'https://www.beveragedaily.com/var/wrbm_gb_food_pharma/storage/images/_aliases/wrbm_large/publications/food-beverage-nutrition/beveragedaily.com/article/2020/09/02/heineken-brewed-with-green-energy-in-the-netherlands/11727623-5-eng-GB/Heineken-brewed-with-green-energy-in-The-Netherlands.png'),
('Sam Adams', 'Water, Malted Barley, Oats, Wheat, Hops, Yeast', 10, 'We recommend this beer for those who want that toasty, earthy bitter kick for their palette. Rich and toasty.', 'beer', 'Bitter', 'fermented', 'https://www.liquor.com/thmb/psG27x1_wK2Pot9eeXm0nMtglLs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/bottle-review_samadamsoctoberfest_720x720-0ca6e2e0a478401a9a7f9d6f9aad9f47.jpg'),
('Sangria', 'Red Wine, Brandy, Oranges, Lemons, Limes, Sugar', 20, 'Sweet, mildly spicy, and very fruity iced drink. Great for those looking for a delicious and hard-hitting drink.', 'wine', 'Bitter, Sweet', 'fermented', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Red_Wine_Sangria_with_lemon%2C_lime%2C_apple%2C_and_orange_served_in_a_glass_-_Evan_Swigart.jpg'),
('Mimosa', 'White Wine, Orange Juice, Orange Slice', 20, 'A crisp, bubbly and sweet-citrus wine that will make you feel fancy.', 'wine', 'Bitter', 'fermented', 'https://bakerbynature.com/wp-content/uploads/2022/04/Strawberry-Mimosas-0-15.jpg'),
('Mulled Wine', 'Red Wine, Brandy, Orange Juice, Cinnamon, Nutmeg, Sugar', 14, 'A red wine that''s fruity, tarty, and smokey all in one.', 'wine', 'Bitter, Dry', 'fermented', 'https://www.wellplated.com/wp-content/uploads/2014/12/Slow-Cooker-Spiced-Wine.jpg'),
('Samuel Smith''s Organic Cider', 'Water, Organic Apple Concentrate, Organic Cane Sugar, Malic Acid, Yeast', 10, 'A taste similar to sweet apples, but is generally watered down for those looking to have a subtle drink.', 'cider', 'Sweet, Bland', 'fermented', 'https://d1ynl4hb5mx7r8.cloudfront.net/wp-content/uploads/2020/06/17163303/84489880.samuels.smith_.organic.cider_.cans_.2300x1059.jpg'),
('Ace Joker Cider', 'Fermented Juice, Carbonated Water, Apple Concentrate, Malic Acid, Sulfite (Preservative)', 14, 'A dry cider made primarily with apple juice, and is allegedly popular with beer and wine enthusiasts.', 'cider', 'Tangy, Dry', 'fermented', 'https://dydza6t6xitx6.cloudfront.net/ci-ace-joker-dry-hard-cider-cbd0fdc1055d9cad.jpeg'),
('Mead', 'Honey, Water, Cinnamon Sticks (Optional)', 20, 'Mead is the classic, medieval drink. This drink is not usually ordered on its own (unless you''re at a Renaissance Fair), but it is served as a foundation for some cocktails. On its own, Mead can taste sweet or dry.', 'mead', 'Sweet, Dry', 'fermented', 'https://bee.net.ua/wp-content/uploads/2017/08/medovuha-300x174.png'),
('Saké', 'Rice, Water, Yeast, Koji', 34, 'Saké is a Japanese alcoholic beverage that tastes similar to White Wine, with a dry taste and smooth feel. Some flavors of Saké can also be fruity and sweet. Because this drink tastes so good, it''s easy to get drunk with.', 'sake', 'Dry, Sweet', 'fermented', 'https://www.japan-guide.com/g21/2037_sake_05.jpg'),
('Gin Martini', 'Gin, Dry Vermouth, Lemon Garnish', 60, 'A classic Gin beverage, this drink tastes very strong and bitter, with a slight hint of sweetness. If ordered ''neat'', you''re asking for your alcohol to be poured straight from the bottle (sans chilling).', 'gin', 'Bitter', 'distilled', 'http://www.pamperedchef.com/iceberg/com/recipe/1445571-lg.jpg'),
('Tom Collins', 'Gin, Lemon Juice, Sugar, Carbonated Water, Lemon Slice Garnish, Maraschino Cherry', 26, 'With lemon as its primary fruit ingredient, this drink tastes a lot like an alcoholic lemonade. Citrusy, fizzy, and refreshing!', 'gin', 'Sour', 'distilled', 'https://www.verywellfit.com/thmb/KHpNEZ6iXp3Oz2BbxJ3d7-J22Ds=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/refreshing-classic-tom-collins-cocktail-537640882-5ab11178eb97de00364210a9.jpg'),
('Negroni', 'Gin, Vermouth Russo, Campari, Orange Peel Garnish', 48, 'Mostly bitter, but has sweet, fruity, and herbal notes. This drink is said to ''open up'' the appetite, which makes it a great pre-dinner beverage.', 'gin', 'Bitter', 'distilled', 'https://www.liquor.com/thmb/EG5Ty48AAylNxWce2yN5Le1ZBLo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/mezcal-negroni-720x720-primary-cdc103ba81e346cfabaebd90909ffc35.jpg'),
('Old Fashioned Brandy', 'Brandy, Angostura Bitter, Orange Slices, Maraschino Cherries, Sugar Cube, Sprite or Club Soda, Orange Slice Garnish', 54, 'The Old Fashioned Brandy has a good bitter flavor, and can be made sweet or sour depending on the soda. A great drink for those looking to have a refined experience.', 'brandy', 'Sweet, Sour', 'distilled', 'https://www.liquor.com/thmb/YIS3-c_-E2ZdCR5kYtPmF8SMN7o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/brandy-old-fashioned-720x720-primary-4416daf388d440fb852f824febdc2557.jpg'),
('Brandy Alexander', 'Cognac, Creme de Cacoa, Heavy Cream, Grated Nutmeg Garnish', 38, 'This dessert drink is a spinoff of the Alexander. It is chilled, and tastes sweet, creamy, and smooth. It''s like drinking an alcoholic milkshake!', 'brandy', 'Sweet', 'distilled', 'https://www.finedininglovers.com/sites/g/files/xknfdk626/files/2020-12/brandy_alexander_cocktail%C2%A9iStock.jpg'),
('Sidecar', 'Cognac, Cointreau (Orange Liqueor), Lemon Juice', 48, 'A Sidecar usually tastes sour or citrusy, (due to the Lemon Juice), with a slightly sweet flavor. A nice, tart beverage to get you feeling good.', 'brandy', 'Sour, Tangy', 'distilled', 'https://i2.wp.com/www.splashoftaste.com/wp-content/uploads/2022/08/sidecar-drink-7.jpg'),
('Old Fashioned Whiskey', 'Whiskey, Bitters, Water, Ice, Simple Syrup, Orange Slice Garnish', 54, 'A sweet whiskey cocktail with slight bitterness and spiciness. A whiskey classic.', 'whiskey', 'Sweet, Spicy', 'distilled', 'https://www.simplyrecipes.com/thmb/s_de1Nuw4ULiHNECVHOCBY5u5Wk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2020__01__Old-Fashioned-Cocktail-LEAD-5-1024x681-aa81a798a156453d80d1f7d41de893ff.jpg'),
('Whiskey Sour', 'Bourbon Whiskey, Egg Whites, Lemon Juice, Gomme Syrup', 30, 'Whiskey Sours are, as the name suggests, very sour. Some bars will vary on the severity of the sourness, but this is a great alternative to the overly sweet or bitter drinks available at most bars.', 'whiskey', 'Sour, Tangy', 'distilled', 'https://www.acouplecooks.com/wp-content/uploads/2019/09/Whiskey-Sour-111s.jpg'),
('Manhattan', 'Whiskey, Sweet or Dry Red Vermouth, Aromatic Bitters, Cherry Garnish', 60, 'A Manhattan is yet another classic, fancy drink. It can be sweet or dry depending on the vermouth, with a hint of bitter and herbal undertones.', 'whiskey', 'Dry, Bitter', 'distilled', 'https://www.liquor.com/thmb/ePeDi1cxFU8mvoIX-xCEiI4lUOM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__liquor__2018__05__10144903__Manhattan-720x720-recipe-9497922907c14d91898f557cb51f2ea3.jpg'),
('Daiquiri', 'Rum, Lime Juice, Syrup or Sugar', 40, 'A classic, frozen drink that will generally have a good balance of sweet and sour flavors. The rum in this drink will taste watered down, so it is a good beverage for those looking to have a strong drink with subtle alcohol.', 'rum', 'Sweet, Sour', 'distilled', 'https://littlesunnykitchen.com/wp-content/uploads/2021/04/Strawberry-Daiquiri-2.jpg'),
('Piña Colada', 'Rum, Coconut Cream, Pineapple Juice', 26, 'A frozen, dessert drink from Puerto Rico, a Piña Colada is a sweet and delicious drink with a decent alcohol percentage. A must-have beverage for those who have never tried alcohol before. Can be served as a virgin (no alcohol), or with Vodka instead of Rum. This is one of our dev''s favorite drinks!', 'rum', 'Sweet', 'distilled', 'https://www.thespruceeats.com/thmb/LI3MXdfPpSL1UbOrcMOXek0u49o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/frozen-pina-colada-recipe-759297-Hero-1-c53f5c55f6b14b3e8fea901076e4b130.jpg'),
('Mojito', 'Rum, Lime Juice, Mint Leaves, Sugar, Club Soda', 26, 'Mojitos originate from Cuba, and often have a Minty, fresh, and sweet flavor. This drink is bubbly and refreshing, and will make you feel like you''re vacationing on a warm, summer day.', 'rum', 'Sweet, Minty', 'distilled', 'https://recipetineats.com/wp-content/uploads/2019/10/Mojito_5.jpg'),
('Margarita', 'Tequila, Cointreau, Lime Juice', 33, 'Margaritas are citrusy and smooth to drink, and some glasses have salt on the rim. This drink is said to have the perfect balance of sour, sweet, bitter, and salty.', 'tequila', 'Sweet, Sour, Bitter', 'distilled', 'https://www.liquor.com/thmb/LvTpxU4_Zjn1EuELMJ6aDijvjBg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__liquor__2017__07__05150949__Frozen-Margarita-720x720-recipe-59566ae60c504508906963b1de69ad25.jpg'),
('El Diablo', 'Tequila, Crème de cassis, Lime Juice, Ginger Beer', 10, 'The El Diablo is a Tequila Mule that has a rereshing and bold flavor. It is described as earthy and zingy thanks to the lime juice and ginger beer.', 'tequila', 'Sour, Bitter', 'distilled', 'https://www.acouplecooks.com/wp-content/uploads/2022/01/El-diablo-cocktail-004.jpg'),
('Tequila Sunrise', 'Tequila, Grenadine Syrup, Orange Juice, Orange or Cherry Garnish', 26, 'A Tequila Sunrise is a must-have tequila drink. It''s bright and sweet, with a burst of tang. If you''re looking for something fresh and fruity, definitely order this on your next night out.', 'tequila', 'Tangy, Sweet', 'distilled', 'https://www.averiecooks.com/wp-content/uploads/2015/08/tequilasunrise-4.jpg'),
('Screwdriver', 'Vodka, Orange Juice', 10, 'Yes, it really IS just Vodka and orange juice. A Screwdriver is a simple and class Vodka cocktail, and the perfect drink to order if you want something simple. It''s sometimes bitter, and usually sweet and tangy.', 'vodka', 'Sweet, Tangy', 'distilled', 'https://mixthatdrink.com/wp-content/uploads/2009/02/screwdriver-drink-featured-735x735.jpg'),
('Cosmopolitan', 'Vodka, Cranberry Juice', 54, 'Cosmopolitans are a good mix of flavors. It''s sweet, fresh, sour, and a little bitter from the Vodka. This drink is great if you''re looking for a light and tangy experience.', 'vodka', 'Sweet, Tangy, Sour', 'distilled', 'https://amandascookin.com/wp-content/uploads/2021/05/Cosmopolitan-Cocktail-RC.jpg'),
('Sea Breeze', 'Vodka, Grapefruit Juice, Cranberry Juice', 20, 'This drink is another refreshing, fruity cocktail. The grapefruit and cranberry juices give the Sea Breeze a nice sweet and sour combination of flavor.', 'vodka', 'Sweet, Sour', 'distilled', 'https://www.liquor.com/thmb/hLHqPxEEaYhytSd5G3eIUjwJExc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/sea-breeze-720x720-recipe-e1e39750d0fe46eeb281de64c93110dd.jpg'),
('Death in the Afternoon', 'Absinthe, Champagne', 25, 'Don''t let the name scare you. This drink, also known as the Hemingway, is a dry and bitter drink that tastes a lot like black licorice. This is a great introduction to absinthe-based cocktails.', 'absinthe', 'Dry, Bitter', 'distilled', 'https://www.acouplecooks.com/wp-content/uploads/2020/12/Death-in-the-afternoon-008s.jpg'),
('Necromancer', 'Absinthe, Elderflower Liqueur, Lillet Blanc, Lemon Juice, Gin', 70, 'Antithesis to its name, the Necromancer is a cocktail that tastes sweet and delicate due to to its floral ingredients that will reset your palette and wake you right up! Be aware of its high alcohol percentage!', 'absinthe', 'Sweet', 'distilled', 'https://www.foodrepublic.com/wp-content/uploads/2014/03/Necromancer.-Photo-by-Alice-Gao.jpeg'),
('Last Resort', 'Absinthe, Massenez Poire Williams, Lime Juice, Syrup, Egg Whites, Grated Nutmeg Garnish', 48, 'A spin on the Last Word, this drink is floral and refreshing. Although this drink is fruity, it does have a strong kick due to the absinthe.', 'absinthe', 'Sweet', 'distilled', 'https://www.liquor.com/thmb/ay97mc8muD5zQ_pZqkwDlzSo2xI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/last-resort-720x720-primary-f3be2f963a504d84a4fc74bf5747d17b.jpg');

INSERT INTO user_establishments (user_uid, yelp_id, name, image) VALUES ('1', 'QArou0r7CmLNPWYRA9ecog', 'McSorleys Old Ale House', 'https://s3-media2.fl.yelpcdn.com/bphoto/1l87JYUuhb--3pKszJ5WsQ/o.jpg');